anchor_version = "0.20.1"
solana_version = "1.9.0"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
merkle_distributor = "MRKGLMizK9XSTaD1d1jbVkdHZbQVCSnPpYiTw9aKQv8"

[programs.devnet]
merkle_distributor = "MRKGLMizK9XSTaD1d1jbVkdHZbQVCSnPpYiTw9aKQv8"

[programs.testnet]
merkle_distributor = "MRKGLMizK9XSTaD1d1jbVkdHZbQVCSnPpYiTw9aKQv8"

[programs.localnet]
merkle_distributor = "MRKGLMizK9XSTaD1d1jbVkdHZbQVCSnPpYiTw9aKQv8"
program_bitmap = "BMP23Y1u4FdGSwknSH7PVswT9ru7f9YsyjqR18pHGmBJ"

[scripts]
test = "yarn mocha"
